### ISSUE TITLE
Picom Blur; gromit-mpx window class name?

### ISSUE THREAD

**Issue by fuzebox1** [bk138/gromit-mpx#112]
When using picom compositor (or others i guess) with background blur enabled the whole screen blurs when activating painting overlay.

I cannot find out the X window class name for the overlay, so that i can make an exception for it in my picom config.

Alternatively i could make an exception for the window type.

How would i go about finding the window class or type of the overlay?
xprop cant do it as it cant grab the mouse in painting mode.

**Comment by fuzebox1** [comment]
I was able to fix it. I put in 'dock' and 'desktop' in blur-background-exclude. Also added "Gromit-mpx" to blur-exclude.
Not sure which did it.

**Comment by bk138** [comment]
NIce to read. OK to close this then?

**Comment by fuzebox1** [comment]
Yeah ill close ty.

**Comment by jraygauthier** [comment]
> I was able to fix it. I put in 'dock' and 'desktop' in blur-background-exclude. Also added "Gromit-mpx" to blur-exclude.
> Not sure which did it.

I tried the proposed solution and it only crashes my picom/compton service which wrongfully made it look like the issue was fixed (the issue won't occur without picom/compton running).

In my particular case, all monitor would turn black as soon as I launched `gromit-mpx`, screen only being refreshed when drawing.

Here's what worked for me without crashing the picom/compton service:


```conf
# ..
shadow-exclude=[ "class_i = 'gromit-mpx'" ];
# ..
```

```bash
$ picom --config /path/to/above-picom.conf
# ..
```

I think such picom/compton compatibility mention would be a nice addition to this project's README and people quite a lot of time.
