### ISSUE TITLE
Cannot deactivate hotkeys: Will refuse to operate

### ISSUE THREAD

**Issue by lenalebt** [bk138/gromit-mpx#162]
**Describe the bug**
I wanted to use a hotkey with a key combination. As this is not possible natively with `gromit-mpx`, I wanted to deactivate the hotkeys (by setting them to `none`, as documented) and use my window manager's capabilities to call `gromit-mpx --toggle` etc. This works as long as a hotkey is set. If I set the hotkey to `""` or `"none"`, gromit-mpx refuses to toggle - not via the context menu, nor via being called on the console.

I now set the hotkeys to the most esoteric ones to have some set as a workaround:
```
HOTKEY = "Pause";
UNDOKEY = "Scroll_Lock";
```

**To Reproduce**
1. Set hotkeys to `"none"` in the config file `gromit-mpx.cfg`, like so:
```
HOTKEY = "";
UNDOKEY = "";
```
2. Open gromit-mpx
3. Call `gromit-mpx --toggle` or select `Toggle painting ()` from the context menu

**Expected Behavior**
gromit-mpx toggles painting mode, but nothing happens (cursor stays the same, no crosshair).

**Environment (please complete the following information):**
 - Gromit-MPX version: 1.4.2-1
 - Flatpak or Distribution-package or Built-from-source: DEB, as included in ubuntu
 - OS and version: Kubuntu 22.04.1 LTS
 - Desktop Environment and version: KDE 5.24.4
 - X11 or Wayland session: X11

**Comment by bk138** [comment]
Yep, can repro. And it crashes on Wayland ;-).

**Comment by bk138** [comment]
OK, some notes to my future self or any interested bugfixer (won't have time to do this in the near future):

* on menu click or cmdline toggle, https://github.com/bk138/gromit-mpx/blob/master/src/input.c#L448 with `dev==NULL` is called in the end, meaning "grab all"
* there is no grab happening as `data->devdatatable` is empty, so no draw cursor appearing
* the table is empty because devices are not added in https://github.com/bk138/gromit-mpx/blob/master/src/input.c#L243 because no hotkey set

**Comment by lenalebt** [comment]
Interesting definition of "not fixing in the near future" :D. Thank you very much for the very fast reaction - and also for the tool overall, it's really nice!

Sent you a donation. Thanks for the good work <3.

**Comment by bk138** [comment]
Yeah in the end it was easier than I thought. Thanks very much for the appreciation!
