### ISSUE TITLE
sway+Xwayland => cannot open display:0

### ISSUE THREAD

**Issue by Simbi0z** [bk138/gromit-mpx#183]
Xwayland autostarts but cannot run gromit
```
gromit-mpx 

(gromit-mpx:3205): Gtk-WARNING **: 13:27:28.104: cannot open display: :0
```
```
ps aux|grep Xway
user         751  0.0  0.8 333876 70520 tty1     Sl+  13:14   0:00 Xwayland :0 -rootless -core -terminate 10 -listenfd 28 -listenfd 30 -displayfd 64 -wm 61
```
Archlinux

gromit-mpx 1.5.1-1
sway 1:1.8.1-3
wlroots 0.16.2-2
xorg-xwayland 23.2.2-1 
wayland 1.22.0-1

**Comment by Simbi0z** [comment]
yes with xeyes and thorium browser running in X mode.

**Comment by bk138** [comment]
I've no idea then, to be honest. Maybe a GTK issue? Can you try the flatpak?

**Comment by bk138** [comment]
Tentatively closing, feel free to post new info here once available.

**Comment by pacmacm** [comment]
Hello,

Confirming this issue on NixOS with Hyprland and XWayland.

**Problem:**
The Nixpkgs-provided `gromit-mpx` (X11 binary) fails to open a display, despite XWayland otherwise being accessible to other X11 applications. The Flatpak version works correctly.

**My Environment:**
*   NixOS 25.11.20250725.7fd36ee (Xantusia)
*   Hyprland 0.50.1
*   `DISPLAY=:1` (matches XWayland)
*   `xhost +si:localuser` used for X access.

**Output:**

```
# XWayland is running and accessible (xterm confirmation):
j@n1:~$ pgrep -af Xwayland
2845 Xwayland :1 -rootless -core -listenfd 49 -listenfd 50 -displayfd 82 -wm 79
r@kohaku:~$ xterm 
xterm: cannot load font "-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso10646-1" # (Launches successfully)
```

```
# gromit-mpx (Nixpkgs X11 binary) fails:
j@n1:~$ gromit-mpx 
(gromit-mpx:XXXXX): Gtk-WARNING **: HH:MM:SS.ms: cannot open display: :1
```

```
# gromit-mpx (Flatpak) works as expected:
j@n1:~$ flatpak run net.christianbeier.Gromit-MPX # (Launches and functions correctly)
```
