### ISSUE TITLE
gromit-mpx ignores config file if it is a symlink

### ISSUE THREAD

**Issue by thisismygitrepo** [bk138/gromit-mpx#214]
I have a dotfile manager where I keep all my config files. I'm pointing from `/home/alex/.var/app/net.christianbeier.Gromit-MPX/config` to the file location in my config repo but it seems that it is ignored. The only way I got it to work is to have the original file there.

can we please be tolerant of symlinks? thanks.

**Comment by bk138** [comment]
That's because an app running inside a flatpak cannot access the host system's filesystem, see https://docs.flatpak.org/en/latest/sandbox-permissions.html - if the pointed-to config file lies somewhere in your homedir, start with `flatpak run --filesystem=home  net.christianbeier.Gromit-MPX` to allow the app to follow the symlink. Or use something like flatseal to set the extra permission permanently.
